data_dir: !!str /home/ncl/yh/fraiwan/fraiwan_16k
label_file: !!str /home/ncl/yh/fraiwan/fraiwan_t11.txt
test_size: !!float 0.4
batch_size: 8
val_batch_size: 16
num_workers: 4
normal_class_label: 0
output_dim: [32, 160]  # [n_mels, spec_width]
sample_rate: 16000
nfft: 401
hop_length: 160
time_mask: 24
freq_mask: 10
mixup_alpha: !!float 10.0